### PR TITLE
Fixes #1

### LINKED ISSUE #1: Add (optional) search/query capability
It would be awesome if this library had similar search functionality to https://pypi.org/project/django-searchable-encrypted-fields/

### PR DESCRIPTION
**Pull request by cdunford**
- Port the SearchField from https://gitlab.com/guywillett/django-searchable-encrypted-fields/ with minor modifications.

Note: I allowed black to format modified files; I can revert the formatting changes if desired.

### CODE REVIEW

**Comment by morlandi** [comment]
@cdunford thank you for your effort, and sorry for not giving a proper response quickly

This library is in use in a critical project where thousands of clients depend on it; for this reason, I have to be very careful when applying improvements and modifications, and an extensive code review and testing are required

If you don't mind, I'll reopen your PR and hopefully process it when time allows

BR, Mario

**Comment by cdunford** [comment]
No worries @morlandi; we're actually using my fork in various places in an application that has about 4 million users :smile:  so it's pretty well tested.

I've actually moved my fork here: https://github.com/Lenders-Cooperative/django-encrypted-json-fields

Would be nice to get merged together though

**Comment by morlandi** [comment]
> we're actually using my fork in various places in an application that has about 4 million users 😄 so it's pretty well tested

I'm sure it is ! 😉  thank you @cdunford 

I will do my best to merge this soon, and maybe also update the "companion" sample project:

https://github.com/morlandi/test_django_encrypted_json_fields

to practice the added search capabilities

**Comment by dgravitate** [comment]
I'm definitely +1 on getting this merged in

**Comment by morlandi** [comment]
Thank you @cdunford for contribution, and sorry for great delay .. I haven't use this library recently

Thank you @dgravitate for reminding me about this PR

I also took the chance to adjust the unit tests for Django 5

**Pull request merged**
